global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "rating-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["rating:11340", "rating-second:11341"]
  - job_name: "books-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["books:10050", "books-second:10051"]
  - job_name: "bff"
    metrics_path: "/book-management-bff/actuator/prometheus"
    static_configs:
      - targets: ["bff:20210"]
